[package]
name = "epic-not-chess-game"
version = "0.1.0"
authors = ["onlymx13 <onlymx13@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
